//! `ContractCatalog` — the `id -> contract` metadata projection (sibling of the
//! `ContractFactory` construction path). Take an id, get its static contract
//! facets (family / inputs / output / cost / outputs / source / slots / volume)
//! WITHOUT building an instance — the path the optimizer prices + prunes config
//! trees with. The catalog IS the contract set viewed by id.
//!
//! Makes families **pluggable from self-declaration**: `family_members(Channel)`
//! asks each id's contract for its `FAMILY`, not a stringly catalog table.
//!
//! The per-id projections (`family_of` … `needs_volume_of`) are GENERATED by
//! `contract_universe!` in `contract_engine` from the ONE member list — the SAME
//! list that generates `ContractFactory`, so the two frontiers cannot drift — and
//! re-exported here. The derived functions below (weights, `family_members`) are
//! hand-written logic over those generated projections.

use crate::engine::contract_engine::IndicatorOutputId;
use crate::engine::indicator_id::IndicatorId;
use crate::contract::{Family, WEIGHTS};
use crate::engine::stream_kind::StreamKind;

// The per-id metadata projections (`family_of` … `needs_volume_of`) are GENERATED
// by `contract_universe!` in `contract_engine` from the ONE member list — the SAME
// list that generates `ContractFactory`, so the two frontiers cannot drift. They
// are re-exported here so `contract_catalog::family_of` (and the rest) stay stable
// import paths, and so the derived logic below reads them by their short names.
pub use crate::engine::contract_engine::{
    cost_of, family_of, inputs_of, needs_time_of, needs_volume_of, output_ids_of, outputs_of,
    slot_default_members_of, slots_of, source_of,
};

/// `true` if `id` is contract-backed (has a self-declared contract). The
/// coverage frontier — grows toward 556 as ids are filled.
pub fn is_contract_backed(id: IndicatorId) -> bool {
    family_of(id).is_some()
}

/// Every id that self-declares membership in `family`. Derived from the
/// contracts, not from a catalog table. Currently ranges over the
/// contract-backed ids only.
pub fn family_members(family: Family) -> Vec<IndicatorId> {
    IndicatorId::all()
        .filter(|id| family_of(*id).map_or(false, |fs| fs.contains(&family)))
        .collect()
}

/// The coordinate system ([`crate::contract::ValueDomain`]) of one of `id`'s outputs —
/// the per-output semantic both strategies (comparability) and render (pane/scale)
/// consume. `None` if `id` is not contract-backed or does not emit `output`.
pub fn output_domain(
    id: IndicatorId,
    output: IndicatorOutputId,
) -> Option<crate::contract::ValueDomain> {
    outputs_of(id)?.iter().find(|o| o.id == output).map(|o| o.domain)
}

/// Every named output the contract exposes in `domain` — the strategy layer's candidate
/// pool for one comparability class, read STRAIGHT from the self-describing contract
/// (`IndicatorId::all()` × `output_ids_of` × `output_domain`). No separate catalog: the
/// contract IS the capability menu (moved from `mli-strategies::generator`, taxonomy
/// 2026-07-03 — the pools are a contract-catalog projection, not a strategy-side shim).
pub fn outputs_in_domain(domain: crate::contract::ValueDomain) -> Vec<IndicatorOutputId> {
    IndicatorId::all()
        .flat_map(|id| output_ids_of(id).iter().copied().map(move |oid| (id, oid)))
        .filter(move |(id, oid)| output_domain(*id, *oid) == Some(domain))
        .map(|(_, oid)| oid)
        .collect()
}

/// Every domain that holds ≥2 named outputs — the crossable comparability classes the
/// strategy layer enumerates over. Built straight from the self-describing contract.
/// Domains with <2 outputs are absent (nothing to cross). `Discrete` is excluded:
/// categorical outputs compared by equality cannot be meaningfully crossed as continuous
/// signals. Moved from `mli-strategies::generator` (taxonomy 2026-07-03).
pub fn crossable_pools() -> Vec<(crate::contract::ValueDomain, Vec<IndicatorOutputId>)> {
    use crate::contract::ValueDomain::{Centered, Count, Flow, Magnitude, Ordinal, Percent, Price, Ratio};
    [Price, Magnitude, Percent, Centered, Count, Ratio, Flow, Ordinal]
        .into_iter()
        .filter_map(|d| {
            let pool = outputs_in_domain(d);
            if pool.len() >= 2 { Some((d, pool)) } else { None }
        })
        .collect()
}


/// Rough per-event input cost of a stream — an order book (N levels) ≫ a bar
/// (OHLCV) ≫ a tick. Derived from the declared `INPUT`, not per indicator.
fn stream_cost(s: StreamKind) -> f64 {
    match s {
        StreamKind::OrderBook => 8.0,
        StreamKind::Bar => 1.0,
        _ => 0.5,
    }
}

/// Total input cost of `id` from its declared `INPUT` streams.
fn input_cost(id: IndicatorId) -> f64 {
    inputs_of(id).map_or(0.0, |ins| ins.iter().copied().map(stream_cost).sum())
}

/// Sum of the MARGINAL costs of `id`'s outputs — restricted to the ids in `consumed`
/// (or every port when `consumed` is `None`). The shared base is NOT here (it lives in
/// `local_cost`); this is only what the taken outputs add on top. Value/byproduct
/// outputs are `FREE` → 0.
fn outputs_marginal(id: IndicatorId, consumed: Option<&[IndicatorOutputId]>) -> f64 {
    outputs_of(id).map_or(0.0, |ps| {
        ps.iter()
            .filter(|p| consumed.map_or(true, |sel| sel.contains(&p.id)))
            .map(|p| p.cost.marginal_cost())
            .sum()
    })
}

/// Raw (unbounded) cost of `id` when `consumed` outputs are taken (`None` = the full
/// surface): shared base (`local_cost`) + Σ marginal of taken outputs + input stream
/// cost + recursive edge cost. Each inner [`Port`] charges its producer's base + the
/// marginals of just the outputs that edge wires — so a node that pulls only a cheap
/// port is weighed cheaply. PERIOD-FREE (structure only). `None` if not contract-backed.
fn raw_cost_of(id: IndicatorId, consumed: Option<&[IndicatorOutputId]>) -> Option<f64> {
    let cost = cost_of(id)?;
    let edges: f64 = cost
        .inner
        .iter()
        .filter_map(|e| raw_cost_of(e.producer, Some(e.outputs)))
        .sum();
    // Each slot reduces to the same recursive consumed-port cost as an edge; the
    // STATIC-weight member is the indicator's own default, read off its typed
    // `defaults()` (`slot_default_members_of`) — no separate `Slot.default` field.
    // A slot charges the member's base + inputs + edges only (no marginal on top,
    // since it consumes the primary FREE output).
    let slots: f64 = slots_of(id)
        .iter()
        .zip(slot_default_members_of(id).iter().copied())
        .filter_map(|(_s, m)| raw_cost_of(m, Some(&[])))
        .sum();
    Some(cost.local_cost() + outputs_marginal(id, consumed) + input_cost(id) + edges + slots)
}

/// The normalized weight in `[0, 1)` of `id` consuming its FULL surface (base + every
/// port's marginal + recursive edges), saturated. PERIOD-FREE — it ranks by structure
/// (store class, update class, recursive ports/members), not by the chosen period.
/// `None` if not contract-backed. For a consumer that wires only some outputs, use
/// [`weight_consumed`] — the honest, port-attributed pruning signal.
pub fn weight_of(id: IndicatorId) -> Option<f64> {
    let raw = raw_cost_of(id, None)?;
    Some(raw / (raw + WEIGHTS.norm_k))
}

/// The normalized weight in `[0, 1)` of consuming only `outputs` of `id` (period-free):
/// `base + Σ marginal(outputs)` + recursive edges, saturated. A consumer
/// wiring just the cheap primary output of a rich producer pays the base only — not
/// its heavy analytics. This is the machine-pruning signal for port-selective
/// edges. `None` if not contract-backed.
pub fn weight_consumed(id: IndicatorId, outputs: &[IndicatorOutputId]) -> Option<f64> {
    let raw = raw_cost_of(id, Some(outputs))?;
    Some(raw / (raw + WEIGHTS.norm_k))
}

/// The `[min, max]` weight of `id` over ALL admissible fillings of its
/// own slots. A slot member is config-chosen and each candidate weighs differently,
/// so the consumer's weight is a RANGE, not a point — `min` uses the lightest
/// candidate of each slot, `max` the heaviest (over the slot's TYPED candidate set,
/// `Slot.candidates`); the
/// `default`-resolved [`weight_of`] sits inside. With no slots the range collapses
/// to a single point. The pruning use: a search sweeps the slot as a dimension, or
/// drops the indicator when even `min` exceeds the budget. `None` if not
/// contract-backed.
pub fn weight_range(id: IndicatorId) -> Option<(f64, f64)> {
    let (lo, hi) = raw_cost_range(id)?;
    let sat = |r: f64| r / (r + WEIGHTS.norm_k);
    Some((sat(lo), sat(hi)))
}

/// The additive (un-normalized) `[min, max]` cost-points of `id` at `period` over ALL
/// admissible slot fillings: `base` (everything EXCEPT this id's own slots, recomputed
/// once) + per slot the lightest / heaviest candidate's recursive cost. The summable
/// budget-currency form behind [`weight_range`] (saturating it gives the normalized
/// range) and [`cost_points_range`]. `None` if not contract-backed.
fn raw_cost_range(id: IndicatorId) -> Option<(f64, f64)> {
    let cost = cost_of(id)?;
    // Base = everything except this id's own slots (recomputed once).
    let edges: f64 = cost
        .inner
        .iter()
        .filter_map(|e| raw_cost_of(e.producer, Some(e.outputs)))
        .sum();
    let base = cost.local_cost() + outputs_marginal(id, None) + input_cost(id) + edges;
    let (mut lo, mut hi) = (base, base);
    for s in slots_of(id) {
        // Candidates are the TYPED admissible set — the `#[slot]` field's
        // `FamilyId::MEMBERS` (e.g. `SmootherId::MEMBERS` = the smoother-safe MAs).
        // The compiler already confined the field to these, so there is no family
        // lookup, no volume filter, no weight cap; the range spans the full typed set.
        // Slots charge base + inputs + edges of each candidate (no marginal, primary FREE).
        let costs: Vec<f64> = s
            .candidates
            .iter()
            .copied()
            .filter_map(|m| raw_cost_of(m, Some(&[])))
            .collect();
        if costs.is_empty() {
            continue;
        }
        lo += costs.iter().copied().fold(f64::INFINITY, f64::min);
        hi += costs.iter().copied().fold(f64::NEG_INFINITY, f64::max);
    }
    Some((lo, hi))
}

// The bag-cost path (`inner_for` / `raw_cost_bagged` / `weight_from_bag` /
// `cost_points_from_bag`) was REMOVED in the bag cut-over. Order-time cost that
// followed the bag's nested config + chosen smoother is gone with the bag; the
// typed cost path (`weight_of` / `weight_range` / `cost_points*`) over static
// default members survives below.

// ─────────────────────────────────────────────────────────────────────────────
// Cost-points — the ADDITIVE budget currency.
//
// `weight_*` return the saturated `[0, 1)` pruning/ranking signal — per-member and
// NON-additive (`raw / (raw + norm_k)`). A budget assembler ("build every strategy
// combination whose TOTAL cost fits N points") needs SUMMABLE units: the functions
// below return the raw, recursively-assembled cost-points BEFORE the saturation. Sum
// them across a strategy's indicators and compare to the budget; the saturated weight
// stays the per-member ranking/pruning signal.
//
// The coefficients (`crate::contract::WEIGHTS`) are a v1 rubric — correct ORDERING by
// structural class (PERIOD-FREE), not measured ns. An empirical calibration wave refits
// them to microbenchmarked per-update time on the target box, so the absolute point
// SCALE is calibration-dependent; the SHAPE (additive, recursive, structural) is stable. See
// `nemo/docs/mli-contract/architecture/contract-dependency-model.md` (cost-points +
// deferred calibration).
// ─────────────────────────────────────────────────────────────────────────────

/// Additive cost-points of `id` consuming its FULL surface (base + every
/// port marginal + recursive edges + default-resolved slots). The summable
/// budget-currency twin of [`weight_of`]. `None` if not contract-backed.
pub fn cost_points(id: IndicatorId) -> Option<f64> {
    // Under `calibrated`: the measured flat ns (already includes nested cost) REPLACES the
    // structural prior wholesale. Feature off → `measured_cost` is `None`, pure prior.
    if let Some(measured) = crate::engine::calibration_shim::measured_cost(id) {
        return Some(measured);
    }
    raw_cost_of(id, None)
}

/// Additive cost-points of consuming only `outputs` of `id` (period-free) — the
/// port-selective budget twin of [`weight_consumed`]. A consumer wiring just the cheap
/// primary output pays the base, not the heavy analytics. `None` if not contract-backed.
pub fn cost_points_consumed(id: IndicatorId, outputs: &[IndicatorOutputId]) -> Option<f64> {
    let raw = raw_cost_of(id, Some(outputs))?;
    // Under `calibrated`: the bench measures the WHOLE indicator, not per-output. Scale the
    // measured flat total by the prior's port-fraction so the selective signal survives (a
    // consumer wiring only the cheap primary still pays less than the full surface).
    if let Some(measured_full) = crate::engine::calibration_shim::measured_cost(id) {
        let raw_full = raw_cost_of(id, None)?;
        if raw_full > 0.0 {
            return Some(measured_full * (raw / raw_full));
        }
    }
    Some(raw)
}

/// Additive `[min, max]` cost-points of `id` over ALL admissible slot
/// fillings — the summable budget twin of [`weight_range`]. The assembler sweeps the
/// slot as a search dimension and prices each end; with no slots the range collapses to
/// a point. `None` if not contract-backed.
pub fn cost_points_range(id: IndicatorId) -> Option<(f64, f64)> {
    let (lo, hi) = raw_cost_range(id)?;
    // Under `calibrated`: scale the prior's slot-fill range by the measured/prior ratio so the
    // range is expressed in the same measured-ns currency as `cost_points`.
    if let Some(measured_full) = crate::engine::calibration_shim::measured_cost(id) {
        let raw_full = raw_cost_of(id, None)?;
        if raw_full > 0.0 {
            let k = measured_full / raw_full;
            return Some((lo * k, hi * k));
        }
    }
    Some((lo, hi))
}

// ─────────────────────────────────────────────────────────────────────────────
// Per-config warmup cost (C3, cost-layer1-closure-plan-2026-07-02, design D1).
//
// `cost_points`/`cost_points_range` above are PERIOD-FREE (structural) or, under
// `calibrated`, priced from `MEASURED_NS` — ONE row per indicator at its DEFAULT
// config. Neither has any notion of `config_hash`. The functions below are the
// per-SWEPT-config complement: keyed by the exact `(id, config_hash)` identity a
// warmup `ColumnKey` dedups by, sourced from `mlq-warmup`'s opt-in real-sweep
// harvest (`MEASURED_NS_PER_CONFIG`). Honest-Err doctrine (plan §0.7): the source
// of a returned cost is ALWAYS explicit — never a silent structural substitution.
// ─────────────────────────────────────────────────────────────────────────────

/// Which table produced a per-config cost estimate — never silently conflated.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum CostSource {
    /// This exact `(id, config_hash)` was harvested from a real warmup sweep
    /// (`MEASURED_NS_PER_CONFIG`, `calibrated` feature only).
    MeasuredConfig,
    /// No harvested entry for this exact config — fell back to the period-free
    /// structural `cost_points(id)` rubric (or, under `calibrated`, `MEASURED_NS`'s
    /// per-DEFAULT-config figure, whichever `cost_points` itself resolves to).
    /// Marked explicitly so a caller can distinguish "measured at this config"
    /// from "structural estimate" — the honest-uncalibrated marker the plan
    /// requires (never a silent fallback dressed up as a measurement).
    StructuralFallback,
}

/// Additive cost-points of `id` AT `config_hash` — the per-config twin of
/// [`cost_points`]. Returns `(points, source)` so the caller always knows whether
/// `points` came from a real per-config harvest or the structural fallback.
/// `None` if `id` is not contract-backed at all (same as every other function
/// here — an uncontracted id has no cost model of any kind).
pub fn cost_points_for_config(id: IndicatorId, config_hash: u64) -> Option<(f64, CostSource)> {
    if let Some(measured) = crate::engine::calibration_shim::measured_cost_for_config(id, config_hash) {
        return Some((measured, CostSource::MeasuredConfig));
    }
    cost_points(id).map(|points| (points, CostSource::StructuralFallback))
}

/// Measured warmup MEMORY weight of `id`, in MB (revived `MemWeight`, 07-01
/// costometer plan Ф3a — heap-live bytes + inline core size at the indicator's
/// DEFAULT config's warmup depth). `None` when the `calibrated` feature is off or
/// `id` has no baked measurement (e.g. not contract-backed, or not yet calibrated).
/// Unlike [`cost_points_for_config`] there is no structural fallback here: memory
/// is not modeled structurally anywhere in this crate, so an absent measurement is
/// honestly `None`, not a made-up number.
pub fn mem_points(id: IndicatorId) -> Option<f64> {
    crate::engine::calibration_shim::measured_mem(id)
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── outputs_in_domain / crossable_pools (moved from mli-strategies::generator,
    // taxonomy 2026-07-03 — domain-comparability pools are a contract-catalog
    // projection) ─────────────────────────────────────────────────────────────

    #[test]
    fn price_domain_pool_from_contract() {
        let price = outputs_in_domain(crate::contract::ValueDomain::Price);
        assert!(price.contains(&IndicatorOutputId::Sma));
        assert!(price.contains(&IndicatorOutputId::Ema));
        // RSI lives in Percent — never in the Price pool.
        assert!(!price.contains(&IndicatorOutputId::Rsi));
        // every pooled output really is Price (the filter is honest).
        assert!(price
            .iter()
            .all(|oid| output_domain(oid.indicator(), *oid) == Some(crate::contract::ValueDomain::Price)));
    }

    /// crossable_pools: Price, Percent, Centered each appear with ≥2 outputs.
    /// A domain with <2 outputs is absent from the result.
    #[test]
    fn crossable_pools_groups_by_domain() {
        use crate::contract::ValueDomain;
        let pools = crossable_pools();
        // Every returned pool has ≥2 outputs.
        for (d, pool) in &pools {
            assert!(pool.len() >= 2, "domain {:?} pool has <2 outputs (should be absent)", d);
        }
        let domains: Vec<ValueDomain> = pools.iter().map(|(d, _)| *d).collect();
        // Price, Percent, Centered all have many outputs — they must appear.
        assert!(domains.contains(&ValueDomain::Price), "Price pool missing");
        assert!(domains.contains(&ValueDomain::Percent), "Percent pool missing");
        assert!(domains.contains(&ValueDomain::Centered), "Centered pool missing");
    }

    #[test]
    fn ma_family_derived_from_contracts() {
        let mas = family_members(Family::MovingAverage);
        for id in [
            IndicatorId::Sma,
            IndicatorId::Ema,
            IndicatorId::Wma,
            IndicatorId::Rma,
        ] {
            assert!(mas.contains(&id), "{id:?} should be in the MovingAverage family");
        }
        // Bollinger is a Channel, not an MA.
        assert!(!mas.contains(&IndicatorId::Bb));
    }

    #[test]
    fn channel_family_has_bollinger() {
        assert!(family_members(Family::Channel).contains(&IndicatorId::Bb));
    }

    #[test]
    fn book_imbalance_is_orderbook_not_oscillator() {
        assert_eq!(
            family_of(IndicatorId::BookImb),
            Some([Family::OrderBook].as_slice())
        );
        assert!(!family_members(Family::Oscillator).contains(&IndicatorId::BookImb));
    }

    #[test]
    fn macd_is_oscillator() {
        // MACD is the canonical oscillator — filling it populates the family.
        assert_eq!(
            family_of(IndicatorId::Macd),
            Some([Family::Oscillator].as_slice())
        );
        assert!(family_members(Family::Oscillator).contains(&IndicatorId::Macd));
    }

    #[test]
    fn coverage_is_complete() {
        // The frontier closed: every IndicatorId is contract-backed. This guard now
        // catches any NEW variant added without a contract (manifest line + impl).
        let total = IndicatorId::all().count();
        let backed = IndicatorId::all().filter(|id| is_contract_backed(*id)).count();
        assert!(backed >= 9, "the contract-backed set is present");
        let missing: Vec<String> = IndicatorId::all()
            .filter(|id| !is_contract_backed(*id))
            .map(|id| format!("{id:?}"))
            .collect();
        assert_eq!(
            backed, total,
            "every IndicatorId must be contract-backed; uncontracted: {missing:?}"
        );
    }

    #[test]
    fn inputs_and_output_projected() {
        // INPUT = streams only (slice lives in Config).
        assert_eq!(inputs_of(IndicatorId::Sma), Some([StreamKind::Bar].as_slice()));
        assert_eq!(
            inputs_of(IndicatorId::BookImb),
            Some([StreamKind::OrderBook].as_slice())
        );
        assert_eq!(
            inputs_of(IndicatorId::LiquidationRate),
            Some([StreamKind::Liquidation].as_slice())
        );
        // Any still-unfilled id projects to None (dynamic — no hardcoded sentinel as the
        // campaign approaches full coverage).
        if let Some(u) = IndicatorId::all().find(|id| !is_contract_backed(*id)) {
            assert_eq!(inputs_of(u), None, "{u:?}: uncontracted id must project inputs to None");
        }
    }

    #[test]
    fn source_axis_matches_input() {
        // The kline source axis exists IFF the indicator consumes a kline FIELD: a
        // contract-backed Bar field indicator carries Some(Field|KlineSlice); a non-bar one
        // (order book / OI / liquidations) has None. The ONE exception is a pure-time core
        // (the `Time` flavor): it consumes the Bar STREAM but draws only the orthogonal
        // wall-clock (`needs_time_of`), not a kline field — so it is Bar-input with None source.
        for id in IndicatorId::all() {
            if !is_contract_backed(id) {
                continue;
            }
            let inputs = inputs_of(id).expect("contract-backed id has inputs");
            let is_bar = inputs.contains(&StreamKind::Bar);
            match source_of(id) {
                Some(_) => assert!(is_bar, "{id:?}: kline source axis but INPUT is not Bar ({inputs:?})"),
                None => assert!(
                    !is_bar || needs_time_of(id),
                    "{id:?}: consumes a Bar but declares no kline source axis (and is not a time core)"
                ),
            }
        }
    }

    #[test]
    fn weight_barometer_assembles_from_structure() {
        let ema = weight_of(IndicatorId::Ema).unwrap();
        let sma = weight_of(IndicatorId::Sma).unwrap();
        let lr = weight_of(IndicatorId::Lr).unwrap();
        // EMA keeps no window store; SMA holds a Vec window (running sum, O(1)); LR holds
        // the window AND rescans it (O(period) -> Linear class). Weight is assembled from
        // those declared stores + update class, never hand-tagged, and is PERIOD-FREE.
        assert!(ema < sma, "no-buffer EMA ({ema}) < Vec-buffer SMA ({sma})");
        assert!(sma < lr, "running-sum SMA ({sma}) < per-bar-rescan LR ({lr})");
        assert!((0.0..1.0).contains(&lr));

        // A budget between SMA and LR admits the cheap MAs and prunes the rescan LR.
        let budget = (sma + lr) / 2.0;
        let admitted: Vec<_> = family_members(Family::MovingAverage)
            .into_iter()
            .filter(|id| weight_of(*id).unwrap_or(1.0) <= budget)
            .collect();
        assert!(admitted.contains(&IndicatorId::Ema), "cheap EMA admitted under budget");
        assert!(!admitted.contains(&IndicatorId::Lr), "heavy LR pruned by the cost budget");

        // Any still-unfilled id has no weight (dynamic sentinel).
        if let Some(u) = IndicatorId::all().find(|id| !is_contract_backed(*id)) {
            assert_eq!(weight_of(u), None, "{u:?}: uncontracted id must have no weight");
        }
    }

    #[test]
    fn port_marginal_cost_semantics() {
        use crate::contract::{OutputCost, Store, StoreKind, UpdateComplexity};
        // A free-rider port (value / byproduct) adds nothing on top of the base.
        assert_eq!(OutputCost::FREE.marginal_cost(), 0.0);
        // A port with its own buffer + per-bar scan adds real (period-free) cost above FREE.
        const HEAVY_STORES: &[Store] = &[Store::window(StoreKind::Deque)];
        let heavy = OutputCost::new(UpdateComplexity::Linear, HEAVY_STORES);
        assert!(heavy.marginal_cost() > 0.0);
        assert!(
            heavy.marginal_cost() > OutputCost::FREE.marginal_cost(),
            "a buffered rescan port costs more than a free port"
        );
    }

    #[test]
    fn rich_producer_is_port_weighted() {
        // Rich Kaufman (Kama) carries heavy base buffers + analytics outputs; lean
        // Kaufman (Ama) is a single FREE value port. Same KAMA value, different
        // surface → the barometer separates them.
        let kama_full = weight_of(IndicatorId::Kama).unwrap();
        let ama = weight_of(IndicatorId::Ama).unwrap();
        assert!(kama_full > ama, "rich Kama ({kama_full}) weighs above lean Ama ({ama})");

        // A consumer taking only Kama's cheap value port pays the base, not the
        // analytics marginals → strictly below the full surface.
        let value_only = weight_consumed(IndicatorId::Kama, &[IndicatorOutputId::KamaLine]).unwrap();
        assert!(value_only < kama_full, "value-only ({value_only}) < full surface ({kama_full})");

        // Wiring the heavy analytics port costs more than value alone.
        let with_variance = weight_consumed(
            IndicatorId::Kama,
            &[IndicatorOutputId::KamaLine, IndicatorOutputId::KamaEfficiencyVariance],
        )
        .unwrap();
        assert!(
            with_variance > value_only,
            "value+variance ({with_variance}) > value-only ({value_only})"
        );
    }

    #[test]
    fn node_edge_propagates_producer_cost() {
        // KamaSlope is a thin node (O(1) slope) but it declares an inner edge to
        // Kama's `value` port. Its weight must therefore carry Kama's heavy base
        // through the edge — far above a cheap leaf like EMA. The dependency is in
        // the contract, not hidden in a held struct.
        let slope = weight_of(IndicatorId::KamaSlope).unwrap();
        let ema = weight_of(IndicatorId::Ema).unwrap();
        assert!(slope > ema, "KamaSlope ({slope}) carries Kama's cost via its edge, above EMA ({ema})");
    }

    #[test]
    fn edges_name_real_producer_ports() {
        // Ports are a STABLE compile-time surface; a consumer's edge depends on
        // CONCRETE typed outputs of a producer. Enforce it: every edge port pointing
        // at an already-contract-backed producer must actually exist on it — no
        // silent mismatch contributing zero marginal. Edges to a not-yet-backed
        // producer are pending; they validate automatically once it is filled. This
        // is what keeps the static weight reliable.
        for id in IndicatorId::all().filter(|id| is_contract_backed(*id)) {
            let cost = cost_of(id).unwrap();
            for edge in cost.inner {
                let Some(producer_ports) = outputs_of(edge.producer) else {
                    continue; // producer not contract-backed yet — pending fill
                };
                for port_id in edge.outputs {
                    assert!(
                        producer_ports.iter().any(|p| p.id == *port_id),
                        "{id:?} edge to {:?} names output {port_id:?} that does not exist on it",
                        edge.producer
                    );
                }
            }
        }
    }

    #[test]
    fn channel_node_consumes_rich_producer_ports() {
        // AdaptiveChannels wires Kama's analytics outputs (efficiency_variance /
        // trend_consistency carry marginals) plus its own channel base; KamaSlope
        // wires only Kama[value]. So the channel node weighs above the slope node —
        // honest port-attributed consumption through declared edges.
        let chan = weight_of(IndicatorId::Adaptivechan).unwrap();
        let slope = weight_of(IndicatorId::KamaSlope).unwrap();
        assert!(
            chan > slope,
            "AdaptiveChannels ({chan}) consumes Kama's rich outputs + own base, above KamaSlope ({slope})"
        );
    }

    #[test]
    fn slot_member_cost_recurses_and_cap_excludes_heavy() {
        // ATR's smoother is a MovingAverage-family SLOT; its cost lands recursively
        // (the default Sma member's value cost) on top of ATR's O(1) TR base — so
        // ATR weighs above a bare Sma.
        let atr = weight_of(IndicatorId::Atr).unwrap();
        let sma = weight_of(IndicatorId::Sma).unwrap();
        assert!(atr > sma, "ATR ({atr}) = TR base + Sma slot member, above bare Sma ({sma})");

        // The candidate set is the TYPED `SmootherId::MEMBERS` (the `+smoother` kernels):
        // light kernels in, heavy/adaptive/volume MAs out — enforced by the field type,
        // carried on the slot for the cost range (no weight cap, no family lookup).
        let slot = slots_of(IndicatorId::Atr)[0];
        assert!(slot.candidates.contains(&IndicatorId::Sma), "Sma is a smoother candidate");
        assert!(slot.candidates.contains(&IndicatorId::Rma), "Rma is a smoother candidate");
        assert!(!slot.candidates.contains(&IndicatorId::Kama), "adaptive Kama is NOT a candidate");
    }

    #[test]
    fn volume_and_heavy_mas_excluded_from_smoother_slots() {
        // A smoother slot is typed to `SmootherId` (the `+smoother`-flagged kernels),
        // so volume MAs (VWMA/VWAP — need volume the scalar slot can't feed) and heavy
        // adaptive MAs (KAMA/FRAMA/VIDYA/…) are excluded by the TYPE — not a runtime
        // filter. The candidate set carries exactly the admissible members.
        let cand = slots_of(IndicatorId::Atr)[0].candidates;
        assert!(cand.contains(&IndicatorId::Sma), "SMA admissible");
        assert!(cand.contains(&IndicatorId::Ema), "EMA admissible");
        assert!(!cand.contains(&IndicatorId::Vwma), "VWMA excluded (volume)");
        assert!(!cand.contains(&IndicatorId::Vwap), "VWAP excluded (volume)");
        assert!(!cand.contains(&IndicatorId::Kama), "KAMA excluded (heavy adaptive)");
        assert!(!cand.contains(&IndicatorId::Frama), "FRAMA excluded (heavy adaptive)");
    }

    #[test]
    fn slot_default_members_are_candidates() {
        // The static-weight slot members (read off the indicator's own typed
        // `defaults()` — no `Slot.default` field) must each be in the slot's CANDIDATE
        // set (the typed field's `FamilyId::MEMBERS`). With typed `*Id` fields this is
        // enforced by the TYPE; verify the resolved default is among the candidates and
        // the member count matches `SLOTS`.
        for id in IndicatorId::all().filter(|id| is_contract_backed(*id)) {
            let slots = slots_of(id);
            let members = slot_default_members_of(id);
            assert_eq!(
                slots.len(),
                members.len(),
                "{id:?}: {} SLOTS vs {} default members (slot_members must match SLOTS order)",
                slots.len(),
                members.len()
            );
            for (slot, member) in slots.iter().zip(members.iter().copied()) {
                assert!(
                    slot.candidates.contains(&member),
                    "{id:?} slot default member {member:?} is not in the slot's candidate set"
                );
            }
        }
    }

    #[test]
    fn contracted_ma_type_users_migrated_to_slots() {
        // Bb (1 center smoother) and Macd (3: fast/slow/signal) carried ma_type;
        // they now declare MovingAverage slots — the ma_type debt in already-
        // contracted indicators is closed.
        assert_eq!(slots_of(IndicatorId::Bb).len(), 1);
        assert_eq!(slots_of(IndicatorId::Macd).len(), 3);
        // AdaptiveChannels' width-ATR smoother is no longer a flat channel slot — it
        // moved INTO the ATR node, reached via Port(Atr) (Model B). So the channel
        // has 0 own slots and an edge to the real ATR node.
        assert_eq!(slots_of(IndicatorId::Adaptivechan).len(), 0);
        assert!(
            cost_of(IndicatorId::Adaptivechan)
                .unwrap()
                .inner
                .iter()
                .any(|e| e.producer == IndicatorId::Atr && e.outputs.contains(&IndicatorOutputId::Atr)),
            "channel edges to the real ATR node for its width"
        );
        for s in slots_of(IndicatorId::Macd) {
            assert!(s.candidates.contains(&IndicatorId::Ema), "Macd slot admits EMA");
        }
        // Macd's three EMA slots land recursively in its weight, above a lone EMA.
        let macd = weight_of(IndicatorId::Macd).unwrap();
        let ema = weight_of(IndicatorId::Ema).unwrap();
        assert!(macd > ema, "Macd ({macd}) carries 3 EMA slots, above a single EMA ({ema})");
    }

    #[test]
    fn slot_makes_consumer_weight_a_range() {
        // ATR's smoother slot admits many MAs, each weighing differently → ATR's
        // weight is a RANGE, not a point: lightest admissible = floor, heaviest =
        // ceiling, and the default-resolved weight sits inside.
        let (lo, hi) = weight_range(IndicatorId::Atr).unwrap();
        assert!(lo < hi, "ATR weight is a range [{lo}, {hi}] over its slot members");
        let def = weight_of(IndicatorId::Atr).unwrap();
        assert!(lo <= def && def <= hi, "default-resolved {def} sits inside [{lo}, {hi}]");

        // A slot-free indicator collapses the range to a single point.
        let (elo, ehi) = weight_range(IndicatorId::Ema).unwrap();
        assert_eq!(elo, ehi, "EMA has no slot -> single-point weight");
    }

    #[test]
    fn weight_consumed_equals_full_for_single_port_ma() {
        // Every average MA exposes one FREE primary output → taking only it costs the
        // same as its full surface (nothing extra to pay for). The split only bites
        // once a producer declares marginal-bearing analytics outputs (e.g. KAMA).
        assert_eq!(
            weight_consumed(IndicatorId::Sma, &[IndicatorOutputId::Sma]),
            weight_of(IndicatorId::Sma)
        );
        assert_eq!(
            weight_consumed(IndicatorId::Ema, &[IndicatorOutputId::Ema]),
            weight_of(IndicatorId::Ema)
        );
        // LR has 4 FREE outputs (value, slope, intercept, r2) — taking just value is fine.
        assert_eq!(
            weight_consumed(IndicatorId::Lr, &[IndicatorOutputId::LrLine]),
            weight_of(IndicatorId::Lr)
        );
    }

    #[test]
    fn cost_points_are_additive_and_unsaturated() {
        // Cost-points are the raw, SUMMABLE form — strictly above the saturated weight
        // (which divides by raw + norm_k), so a budget assembler can add them.
        let sma = cost_points(IndicatorId::Sma).unwrap();
        assert!(sma > weight_of(IndicatorId::Sma).unwrap(), "raw points exceed the saturated weight");
        // Ordering asserts hold for the STRUCTURAL rubric only. Under `calibrated`,
        // `cost_points` returns MEASURED wall-clock ns — a measurement answers to the
        // reconciliation gates (C3), not to a-priori orderings; dev-box jitter can
        // legitimately flip Ema/Sma between bakes (observed 2026-07-03: Ema 11.1 vs
        // Sma 5.8 on one bake, inverted on the prior one). Asserting it here would
        // make every re-bake a coin-flip test failure.
        #[cfg(not(feature = "calibrated"))]
        {
            let ema = cost_points(IndicatorId::Ema).unwrap();
            assert!(ema < sma, "EMA cheaper than SMA in points too (same ordering as weight)");
        }
        // The port-selective twin: taking only the cheap value port costs <= full.
        let kama_full = cost_points(IndicatorId::Kama).unwrap();
        let kama_value = cost_points_consumed(IndicatorId::Kama, &[IndicatorOutputId::KamaLine]).unwrap();
        assert!(kama_value < kama_full, "value-only points below full surface");
        // Any still-unfilled id has no points (dynamic sentinel).
        if let Some(u) = IndicatorId::all().find(|id| !is_contract_backed(*id)) {
            assert_eq!(cost_points(u), None, "{u:?}: uncontracted id must have no cost points");
        }
    }

    #[test]
    fn cost_points_range_brackets_order_and_collapses_without_slots() {
        // ATR's smoother slot makes its points a RANGE; the default-resolved order and a
        // concrete bagged order both land inside it — the budget twin of weight_range.
        let (lo, hi) = cost_points_range(IndicatorId::Atr).unwrap();
        assert!(lo < hi, "ATR points are a range over its smoother slot");
        let def = cost_points(IndicatorId::Atr).unwrap();
        assert!(lo <= def && def <= hi, "default-resolved points {def} inside [{lo}, {hi}]");
        // Slot-free EMA collapses the range to a single point.
        let (elo, ehi) = cost_points_range(IndicatorId::Ema).unwrap();
        assert_eq!(elo, ehi, "EMA has no slot -> single-point cost");
    }

    #[test]
    fn cost_points_for_config_uncalibrated_marker_is_explicit() {
        // No harvested `MEASURED_NS_PER_CONFIG` entry exists for this made-up
        // config_hash (the committed table is empty until a real sweep is baked, and
        // even once populated this specific hash won't collide) — the fallback to the
        // structural prior must be reported EXPLICITLY via `CostSource`, never as an
        // indistinguishable number (plan §0.7 honest-uncalibrated gate).
        let (points, source) = cost_points_for_config(IndicatorId::Sma, 0xDEAD_BEEF).unwrap();
        assert_eq!(source, CostSource::StructuralFallback);
        assert_eq!(points, cost_points(IndicatorId::Sma).unwrap(), "fallback == cost_points(id)");

        // Uncontracted ids still have no cost model at all (None, not a fallback marker).
        if let Some(u) = IndicatorId::all().find(|id| !is_contract_backed(*id)) {
            assert_eq!(cost_points_for_config(u, 0), None, "{u:?}: uncontracted id has no per-config cost");
        }
    }

    #[test]
    fn mem_points_is_honestly_absent_without_calibrated_feature() {
        // MemWeight revival (Ф3a): with the `calibrated` feature off (this test build's
        // default), NO memory table is embedded at all — `mem_points` must return `None`,
        // never a fabricated 0.0 (there is no structural memory model to fall back to,
        // unlike `cost_points_for_config`).
        #[cfg(not(feature = "calibrated"))]
        assert_eq!(mem_points(IndicatorId::Sma), None);
    }

    #[test]
    fn machine_defaults_pass_own_valid_params_universe() {
        // The permanent invariant this test guards: ANY contract-backed indicator's
        // `machine_defaults()` order must build via the SAME gate every real consumer
        // goes through — `IndicatorOrder::build_solo`, which runs `Config::valid_params`
        // on the RAW (possibly still-`Many`) config. `Param::resolved()` on a `Many` axis
        // picks its FIRST value (the min corner) — so this is exactly the point a
        // dual-period indicator's own ordering rule (fast < slow) must not reject.
        //
        // `mli-strategies::enumerate::leaf_for` builds every machine-generator production
        // (zscore_cross / slope_sign / osc_threshold / …) straight off `from_machine_defaults`
        // without ever iterating the cube first — so a `machine_defaults()` whose first point
        // fails `valid_params` silently kills that indicator's whole strategy batch via `?`.
        // Was found doing so for VoVr / Ama / Kvo / Logicsign (2026-07-03); this test is the
        // permanent regression gate for the whole universe, not just those four.
        use crate::engine::contract_engine::IndicatorOrder;

        let mut offenders: Vec<String> = Vec::new();
        for id in IndicatorId::all() {
            let Some(order) = IndicatorOrder::from_machine_defaults(id) else {
                continue; // not contract-backed — no machine_defaults to check
            };
            if let Err(reason) = order.build_solo() {
                offenders.push(format!("{id:?}: {reason:?}"));
            }
        }
        assert!(
            offenders.is_empty(),
            "machine_defaults() must pass its own valid_params for every contract-backed \
             indicator (min-corner build via build_solo, the real consumer path); offenders:\n{}",
            offenders.join("\n")
        );
    }

    /// Deterministic zigzag OHLCV bars — same generator shape as `Ewa`'s test fixture
    /// (`indicators::regime::ewa::tests::zigzag_bars`), reused here so the whole
    /// universe warms up on a realistic price structure (swing pivots, non-degenerate
    /// deltas) rather than a flat or monotonic series that would mask division-by-zero
    /// bugs at small periods.
    fn zigzag_bars(n: usize) -> Vec<(f64, f64, f64, f64, f64)> {
        let mut bars = Vec::with_capacity(n);
        let mut price = 100.0_f64;
        for i in 0..n {
            let next = if i % 2 == 0 { price * 1.03 } else { price * 0.98 };
            let (open, close) = (price, next);
            let high = open.max(close) * 1.002;
            let low = open.min(close) * 0.998;
            bars.push((open, high, low, close, 1000.0));
            price = next;
        }
        bars
    }

    /// A1 2026-07-04 gate: the runtime twin of `machine_defaults_pass_own_valid_params_universe`.
    /// That test only proves the min-corner config BUILDS (`valid_params` + `create` succeed);
    /// it says nothing about what happens once the built core actually RUNS at period=1 —
    /// a rolling std/variance/MAD window of width 1 (or 0 after a `period - 1` sizing) is a
    /// classic division-by-zero / NaN trap that only shows up on real feed, not on construction.
    ///
    /// For every contract-backed `IndicatorId`, build its `machine_defaults()` min corner via
    /// `build_solo()` (same real-consumer gate), feed it 512 deterministic zigzag bars (the
    /// `Ewa` fixture shape), and after every feed assert every SCALAR output (`read`, `grid`
    /// returns `None` for these — the table surface has its own shape and is checked
    /// separately) is finite. Table outputs are read via `grid` and merely asserted `Some`
    /// once the core reports ready — a table's cell-level finiteness is out of scope here.
    ///
    /// `Bar`-only: indicators whose `INPUT` does not include `StreamKind::Bar` never see this
    /// feed and would sit permanently not-ready — irrelevant noise for a PERIOD-floor policy
    /// change, so they are skipped rather than asserted on a feed they cannot consume.
    ///
    /// A single indicator's PANIC (an unguarded `assert!`/index/arithmetic bug inside the
    /// core) must not abort the whole sweep — `catch_unwind` collects it as an offender like
    /// any other failure so one bad core doesn't hide the rest of the universe's report.
    ///
    /// `HalfLifeMr` is EXEMPT from the finite check (NaN still bans it): its own doc
    /// (`hl = -ln(2)/ln(phi)`) defines `f64::INFINITY` as the honest "no mean-reversion
    /// detected" sentinel when the fitted AR(1) `phi` falls outside `(0, 1)` — exactly what
    /// this fixture's near-perfectly anti-persistent zigzag alternation (φ < 0) produces at
    /// ANY window size (its `window` is internally clamped `.max(20)`, so this is a data-shape
    /// artifact, not a period-floor bug). Asserting finiteness there would fail a documented
    /// domain value, not catch a real one.
    #[test]
    fn machine_defaults_min_corner_runtime_smoke() {
        use crate::contract::MarketSample;
        use crate::engine::contract_engine::IndicatorOrder;

        let bars = zigzag_bars(512);
        let mut covered = 0usize;
        let mut offenders: Vec<String> = Vec::new();

        // Suppress the default panic-to-stderr printer while probing — offenders are
        // reported through the assertion message, not console noise from `catch_unwind`.
        let default_hook = std::panic::take_hook();
        std::panic::set_hook(Box::new(|_| {}));

        for id in IndicatorId::all() {
            let Some(inputs) = inputs_of(id) else {
                continue; // not contract-backed
            };
            if !inputs.contains(&StreamKind::Bar) {
                continue; // this feed cannot reach it — out of scope for this smoke
            }
            let Some(order) = IndicatorOrder::from_machine_defaults(id) else {
                continue;
            };
            covered += 1;

            let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
                let mut factory = order.build_solo().map_err(|e| format!("build_solo: {e:?}"))?;
                for &(o, h, l, c, v) in &bars {
                    factory.feed(0, MarketSample::Bar { open: o, high: h, low: l, close: c, volume: v });
                    if !factory.is_ready() {
                        continue;
                    }
                    for out in output_ids_of(id) {
                        if let Some(grid) = factory.grid(*out) {
                            if grid.rows() == 0 {
                                return Err(format!("{out:?}: ready table output has zero rows"));
                            }
                            continue;
                        }
                        let v = factory.read(*out);
                        if v.is_nan() {
                            return Err(format!("{out:?}: NaN after ready"));
                        }
                        if v.is_infinite() && id != crate::engine::indicator_id::IndicatorId::HalfLifeMr {
                            return Err(format!("{out:?}: non-finite value {v} after ready"));
                        }
                    }
                }
                Ok(())
            }));

            match result {
                Ok(Ok(())) => {}
                Ok(Err(reason)) => offenders.push(format!("{id:?}: {reason}")),
                Err(panic) => {
                    let msg = panic
                        .downcast_ref::<&str>()
                        .map(|s| s.to_string())
                        .or_else(|| panic.downcast_ref::<String>().cloned())
                        .unwrap_or_else(|| "<non-string panic payload>".to_string());
                    offenders.push(format!("{id:?}: PANIC: {msg}"));
                }
            }
        }

        std::panic::set_hook(default_hook);

        assert!(covered > 0, "no Bar-consuming contract-backed indicator was probed — harness broken");
        assert!(
            offenders.is_empty(),
            "machine_defaults() min-corner must run cleanly to finite outputs over 512 \
             zigzag bars for every Bar-consuming contract-backed indicator ({covered} covered); \
             offenders:\n{}",
            offenders.join("\n")
        );
    }

}
