//! Box-free contract factory — re-export shim over the generated engine.
//!
//! [`ContractFactory`] (the box-free build+run enum) is GENERATED by
//! `contract_universe!` in [`crate::indicators::contract_engine`] from the ONE
//! member list. This module re-exports it so `contract_factory::ContractFactory`
//! stays a stable path, and hosts the box-free factory's e2e tests (the harness that
//! clones how a configurator builds + runs indicators — NO mlq dependency).
//!
//! Build path: `IndicatorOrder::<Variant>(Config).build() -> Result<ContractFactory>`
//! — a box-free typed order carrying the member's OWN `Config` (the assembly-time dual
//! of `ContractFactory`). The order DEMANDS a complete config (no `Default` on the
//! compute path); cold-start configs come from `Render::defaults()`. `create(Config)`
//! resolves the chosen source + builds the core. The periods-only `from_id` is GONE.

pub use crate::engine::contract_engine::ContractFactory;

// `MarketSample` is used in feed tests via `use super::*`.
#[cfg(test)]
use crate::contract::MarketSample;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::types::{Liquidation, OpenInterest, OrderBook, OrderBookLevel, TradeSide};

    // --- helpers ---

    fn make_book(bids: &[(f64, f64)], asks: &[(f64, f64)]) -> OrderBook {
        OrderBook {
            bids: bids.iter().map(|&(p, s)| OrderBookLevel::new(p, s)).collect(),
            asks: asks.iter().map(|&(p, s)| OrderBookLevel::new(p, s)).collect(),
            timestamp: 0,
            ..Default::default()
        }
    }

    fn make_liq(ts: i64) -> Liquidation {
        Liquidation {
            symbol: String::new(),
            side: TradeSide::Buy,
            price: 30_000.0,
            quantity: 0.1,
            timestamp: ts,
            value: None,
            ..Default::default()
        }
    }

    fn make_oi(val: f64) -> OpenInterest {
        OpenInterest { open_interest: val, open_interest_value: None, timestamp: 0, ..Default::default()}
    }

    // --- multi-stream feed routing (the keystone of the box-free factory) ---

    /// `feed` routes `MarketSample::OrderBook` correctly through `BookImbalanceRatio`
    /// and produces bit-for-bit identical values to a hand-built instance.
    #[test]
    fn feed_routes_orderbook_boxfree() {
        use crate::indicators::book::imbalance::BookImbalanceRatio;
        use crate::engine::streams::order_book_consumer::OrderBookConsumer;
        use crate::engine::contract_engine::IndicatorOrder;

        let books = vec![
            make_book(&[(100.0, 30.0)], &[(101.0, 10.0)]),
            make_book(&[(100.0, 10.0)], &[(101.0, 30.0)]),
            make_book(&[(100.0, 15.0), (99.0, 5.0)], &[(101.0, 15.0), (102.0, 5.0)]),
        ];

        let mut via_factory = IndicatorOrder::BookImb(<<BookImbalanceRatio as crate::contract::Indicator>::Config as crate::contract::Config>::defaults()).build_solo().unwrap();
        let mut direct = BookImbalanceRatio::new();

        for book in &books {
            let factory_val = via_factory.feed(0, MarketSample::OrderBook(book));
            let direct_val = direct.update_orderbook(book);
            assert_eq!(
                factory_val, direct_val,
                "factory BookImbalanceRatio value must match direct: {factory_val:?} != {direct_val:?}"
            );
        }

        assert!(via_factory.is_ready());
        assert!(direct.is_ready());
    }

    /// `feed` routes `MarketSample::Liquidation` correctly through `LiquidationRate`.
    #[test]
    fn feed_routes_liquidation_boxfree() {
        use crate::engine::streams::liquidation_consumer::LiquidationConsumer;
        use crate::indicators::liquidations::liquidation_rate::LiquidationRate;
        use crate::engine::contract_engine::IndicatorOrder;

        let liqs = vec![make_liq(0), make_liq(1_000), make_liq(5_000)];

        let mut via_factory = IndicatorOrder::LiquidationRate(<<LiquidationRate as crate::contract::Indicator>::Config as crate::contract::Config>::defaults()).build_solo().unwrap();
        let mut direct = LiquidationRate::new(60_000);

        for liq in &liqs {
            let factory_val = via_factory.feed(0, MarketSample::Liquidation(liq));
            let direct_val = direct.update_liquidation(liq);
            assert_eq!(
                factory_val, direct_val,
                "factory LiquidationRate value must match direct: {factory_val:?} != {direct_val:?}"
            );
        }

        assert!(via_factory.is_ready());
        assert!(direct.is_ready());
    }

    /// `feed` routes `MarketSample::OpenInterest` correctly through `OiZScore`.
    #[test]
    fn feed_routes_open_interest_boxfree() {
        use crate::indicators::open_interest::oi_z_score::OiZScore;
        use crate::engine::streams::open_interest_consumer::OpenInterestConsumer;
        use crate::engine::contract_engine::IndicatorOrder;

        let oi_vals = [100.0f64, 100.0, 100.0, 100.0, 150.0];

        let mut via_factory = {
            let mut c = <<OiZScore as crate::contract::Indicator>::Config as crate::contract::Config>::defaults();
            c.window = crate::contract::Param::Solo(5);
            IndicatorOrder::OiZScore(c).build_solo().unwrap()
        };
        let mut direct = OiZScore::new(5);

        for &v in &oi_vals {
            let oi = make_oi(v);
            let factory_val = via_factory.feed(0, MarketSample::OpenInterest(&oi));
            let direct_val = direct.update_oi(&oi);
            assert_eq!(
                factory_val, direct_val,
                "factory OiZScore value must match direct: {factory_val:?} != {direct_val:?}"
            );
        }
    }

    /// Parity: `ContractFactory` built via `Trima`, `Alma`, `Bb` routes must produce
    /// bit-for-bit identical values to instances built directly through the typed
    /// `Render::defaults()` + period-override + `create` path.
    #[test]
    fn feed_routes_folded_indicators_boxfree() {
        use crate::indicators::average::alma::Alma;
        use crate::indicators::average::trima::Trima;
        use crate::indicators::channels::bollinger_bands::BollingerBands;
        use crate::engine::contract_engine::IndicatorOrder;
        use crate::contract::Indicator as _;

        let bars: Vec<(f64, f64, f64, f64, f64)> = (0..30)
            .map(|i| {
                let c = 100.0 + (i as f64 * 0.3).sin() * 8.0;
                (c + 1.5, c + 3.0, c - 1.5, c, 1000.0 + i as f64 * 10.0)
            })
            .collect();

        // --- Trima parity ---
        let mut via_factory_trima = {
            let mut c = <<Trima as crate::contract::Indicator>::Config as crate::contract::Config>::defaults();
            c.period = crate::contract::Param::Solo(10);
            IndicatorOrder::Trima(c).build_solo().unwrap()
        };
        let mut direct_trima = {
            let mut c = <<Trima as crate::contract::Indicator>::Config as crate::contract::Config>::defaults();
            c.period = crate::contract::Param::Solo(10);
            Trima::create(c)
        };
        for &(o, h, l, c, v) in &bars {
            via_factory_trima.update_bar(o, h, l, c, v);
            // Trima is a pure Field core now: the factory resolves Close and feeds the
            // scalar, so the direct core is fed the close to match.
            direct_trima.feed(c);
            let fv = via_factory_trima.primary();
            let dv = direct_trima.value();
            assert_eq!(fv, dv, "Trima factory != direct: {fv:?} != {dv:?}");
        }

        // --- Alma parity ---
        let mut via_factory_alma = {
            let mut c = <<Alma as crate::contract::Indicator>::Config as crate::contract::Config>::defaults();
            c.period = crate::contract::Param::Solo(10);
            IndicatorOrder::Alma(c).build_solo().unwrap()
        };
        let mut direct_alma = {
            let mut c = <<Alma as crate::contract::Indicator>::Config as crate::contract::Config>::defaults();
            c.period = crate::contract::Param::Solo(10);
            Alma::create(c)
        };
        for &(o, h, l, c, v) in &bars {
            via_factory_alma.update_bar(o, h, l, c, v);
            direct_alma.feed(c);
            let fv = via_factory_alma.primary();
            let dv = direct_alma.value();
            assert_eq!(fv, dv, "Alma factory != direct: {fv:?} != {dv:?}");
        }

        // --- BollingerBands parity ---
        let mut via_factory_bb = {
            let mut c = <<BollingerBands as crate::contract::Indicator>::Config as crate::contract::Config>::defaults();
            c.period = crate::contract::Param::Solo(14);
            IndicatorOrder::Bb(c).build_solo().unwrap()
        };
        let mut direct_bb = {
            let mut c = <<BollingerBands as crate::contract::Indicator>::Config as crate::contract::Config>::defaults();
            c.period = crate::contract::Param::Solo(14);
            BollingerBands::create(c)
        };
        for &(o, h, l, c, v) in &bars {
            // BB is a pure core now: the factory resolves the default Close source and feeds
            // the scalar, so the direct core is fed the close to match.
            via_factory_bb.update_bar(o, h, l, c, v);
            direct_bb.feed(c);
            // primary() reads BB's FIRST declared output (`upper`), so compare upper-to-upper.
            let fv = via_factory_bb.primary();
            let dv = direct_bb.upper();
            assert_eq!(fv, dv, "BollingerBands factory != direct: {fv:?} != {dv:?}");
        }
    }

    /// Feeding a `MarketSample::Bar` to a `BookImbalanceRatio` variant is a no-op:
    /// returns the current value unchanged, no panic, no state change.
    #[test]
    fn foreign_sample_is_noop() {
        use crate::engine::contract_engine::IndicatorOrder;
        use crate::indicators::book::imbalance::BookImbalanceRatio;
        let mut inst = IndicatorOrder::BookImb(<<BookImbalanceRatio as crate::contract::Indicator>::Config as crate::contract::Config>::defaults()).build_solo().unwrap();

        // Not ready yet — feed a book first so we have a known value.
        let book = make_book(&[(100.0, 20.0)], &[(101.0, 10.0)]);
        inst.feed(0, MarketSample::OrderBook(&book));
        let primary_after_book = inst.primary();
        assert!(inst.is_ready());

        // Now feed a Bar (wrong stream) — must be a no-op.
        inst.feed(0, MarketSample::Bar {
            open: 1.0,
            high: 2.0,
            low: 0.5,
            close: 1.5,
            volume: 100.0,
        });
        let primary_after_bar = inst.primary();

        assert_eq!(
            primary_after_book, primary_after_bar,
            "feeding a Bar to BookImbalanceRatio must be a no-op (value unchanged)"
        );
        // State must not have changed: is_ready() still true, same value.
        assert!(inst.is_ready());
    }

    /// Frontier parity: `is_contract_backed` and `ContractFactory::is_migrated` must
    /// agree on every `IndicatorId` — nothing half-wired.
    #[test]
    fn frontier_contract_eq_factory() {
        use crate::engine::contract_catalog::is_contract_backed;
        use crate::engine::indicator_id::IndicatorId;

        for id in IndicatorId::all() {
            assert_eq!(
                is_contract_backed(id),
                ContractFactory::is_migrated(id),
                "{id:?}: is_contract_backed != is_migrated (half-wired)"
            );
        }
    }

    /// The sweep keystone (engine half of the generator bridge): a swept `IndicatorOrder`
    /// reports its cube size, `iter()` expands to that many resolved single-point orders, and
    /// `build_many()` materializes exactly that many concrete factories. This is the typed
    /// surface the strategy generator's AST leaf consumes — `order.cube_size()`/`build_many()`
    /// replacing the stringly `param_metadata` axis read.
    #[test]
    fn indicator_order_cube_expands_and_builds() {
        use crate::engine::contract_engine::{IndicatorOrder, SmootherChoice, SmootherId};
        use crate::engine::indicator_id::IndicatorId;
        use crate::engine::ohlcv_field::OhlcvField;
        use crate::indicators::momentum::rsi::RsiConfig;
        use crate::contract::Param;

        // All-`Solo` cold-start order → exactly one cube point.
        let solo = IndicatorOrder::from_defaults(IndicatorId::Rsi).unwrap();
        assert_eq!(solo.cube_size(), 1);
        assert_eq!(solo.iter().count(), 1);
        assert_eq!(solo.build_many().valid.len(), 1);

        // Swept: period {5,10,15,20,25}(5) × source {Close,High}(2) × kind {Rma,Sma}(2) = 20.
        let swept = IndicatorOrder::Rsi(RsiConfig {
            period: Param::range(5, 25, 5),
            source: Param::many(vec![OhlcvField::Close, OhlcvField::High]),
            smoother: Param::many(vec![
                SmootherChoice::follow(SmootherId::Rma),
                SmootherChoice::follow(SmootherId::Sma),
            ]),
        });
        assert_eq!(swept.cube_size(), 20);

        let expanded: Vec<IndicatorOrder> = swept.iter().collect();
        assert_eq!(expanded.len(), 20);
        // every expanded order is a single resolved point (all-`Solo`)...
        assert!(expanded.iter().all(|o| o.cube_size() == 1));
        // ...and build_cube materializes all 20 concrete factories.
        assert_eq!(swept.build_many().valid.len(), 20);
    }

    /// The generator's typed sweep override: `from_defaults` is a Solo (render) order;
    /// `with_period` overlays a swept period axis WITHOUT naming the concrete config — the
    /// strategy generator's path (it always overrides). Periodless configs are a no-op.
    #[test]
    fn indicator_order_with_period_overrides() {
        use crate::engine::contract_engine::IndicatorOrder;
        use crate::engine::indicator_id::IndicatorId;
        use crate::contract::Param;

        // Period-bearing (RSI): Solo default (cube 1) -> with_period(5..50/5) overlays 10 values.
        let swept = IndicatorOrder::from_defaults(IndicatorId::Rsi)
            .unwrap()
            .with_period(Param::range(5, 50, 5));
        assert_eq!(swept.cube_size(), 10, "with_period overlays the swept period axis");
        assert_eq!(swept.iter().count(), 10);

        // Periodless (BOP — a field-less unit config): with_period is a no-op via the
        // `Config::set_primary_period` trait default; the order stays a single point.
        let bop = IndicatorOrder::from_defaults(IndicatorId::Bop)
            .unwrap()
            .with_period(Param::range(5, 50, 5));
        assert_eq!(bop.cube_size(), 1, "periodless config: with_period no-op, stays cube 1");
    }
}
