//! The contract engine — the box-free `ContractFactory` (generated by `contract_universe!`
//! in `contract_engine`) plus the typed id/value/field/stream surface it builds over, and the
//! per-stream consumer traits under `streams/`. Every indicator AND detector in the catalog
//! is registered here, regardless of which category folder its impl lives in.

pub mod calibration_shim;
pub mod contract_engine;
pub mod contract_catalog;
pub mod contract_factory;
pub mod indicator_id;
pub mod matrix_grid;
pub mod ohlcv_field;
pub mod stream_kind;
pub mod time_window;

pub mod streams;

pub use matrix_grid::{AxisLabels, Label, MatrixCell, MatrixGrid};
pub use ohlcv_field::OhlcvField;
pub use stream_kind::StreamKind;
